services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './:/app'
    env_file:
      - .env
    ports:
      - ${HOST_HTTP_PORT}:${HTTP_PORT}
    networks:
      - tracker

  database:
    image: postgres
    env_file:
      - .env
    ports:
      - ${POST_EXTERNAL_PORT}:${POST_INTERNAL_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - tracker

networks:
  tracker: